# CI: build & upload dist artifact, Deploy: download artifact and deploy static files to Vercel
# Requer secrets no GitHub: VERCEL_TOKEN, VERCEL_ORG_ID, VERCEL_PROJECT_ID
name: CI & Deploy static to Vercel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    name: Test, Build & Storybook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests (coverage)
        run: npm run test:run

      - name: Build app
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - name: Upload storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook
          path: storybook-static

  deploy:
    name: Deploy dist to Vercel (artifact)
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Show dist contents (debug)
        run: |
          echo "Contents of ./dist:"
          ls -la dist

      - name: Install Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Deploy to Vercel (using vercel CLI via npx)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npx --yes vercel@latest --token "$VERCEL_TOKEN" --prod --confirm --scope "$VERCEL_ORG_ID" --project "$VERCEL_PROJECT_ID" ./dist